In [1]:
import numpy as np

In [2]:
import numpy as np

# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5])

# Print the array
print(arr)


[1 2 3 4 5]


In [3]:
arr = np.array([[1,2,3,4], [5,6,7,8]])
arr.max()

np.int64(8)

In [7]:
arr = np.array([1, 2, 3, 4, 5, 6])

# Reshape to 2 rows, 3 columns
reshaped_arr = arr.reshape(2, 3)
reshaped_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
print("Original Array:")
print(arr)
print("\nReshaped Array (2x3):")
print(reshaped_arr)

Original Array:
[1 2 3 4 5 6]

Reshaped Array (2x3):
[[1 2 3]
 [4 5 6]]


In [9]:
arr = np.linspace(0,1,2)
arr

array([0., 1.])

In [10]:
arr = np.linspace(0,1,5,)
arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [12]:
array1 = np.array([[1,2,3,],[4,5,6]])
array1  #Printing array

array([[1, 2, 3],
       [4, 5, 6]])

In [2]:
array1

[[1, 2, 3], [4, 5, 6]]

In [10]:
array2 = np.array([1,2.23,3,4,5,6,7,8])
array2

array([1.  , 2.23, 3.  , 4.  , 5.  , 6.  , 7.  , 8.  ])

In [ ]:
array2.dtype
#gives the datatype of elements in array

dtype('float64')

In [ ]:
array2.ndim
# gives the dimension of array

1

In [14]:
array1.ndim

2

In [ ]:
#takes square of array
Square = array1 ** 2
Square

array([[ 1,  4,  9],
       [16, 25, 36]])

In [ ]:
array1 = np.array([[1,2,3],[4,5,6]])
array1
array1.ndim
# prints dimension of array

2

In [22]:
array2[2]
#print the elemet of 2nd index

np.float64(3.0)

In [23]:
array2[-1]
#print last element of array

np.float64(8.0)

In [ ]:
array3 = np.arange(1,17)
array3
#print array in the range of 1- 17

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [ ]:
a= array3.reshape(4,4)
print(a)
#print array in matrix form of 4 * 4

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
b= np.array([[1,2,3],[4,5,6],[7,8,9]])
c = np.array([[9,8,7],[6,5,4],[3,2,1]])
print(b)# print array
print(c)
d= b+c
print(d) #addition of array

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]
[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [ ]:
a1 = b/c #print division of 2 arrays
print(a1)

[[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]
