In [48]:
import numpy as np

In [ ]:
#print the array using range func
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#declare the array and printing the array 
arr2 = np.array([[1,2,3],[2,3,4],[3,4,5]])
arr2

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [51]:
zeros_arr = np.zeros(5)
zeros_arr

array([0., 0., 0., 0., 0.])

In [52]:
zeros_arr = zeros_arr.astype(int)
zeros_arr

array([0, 0, 0, 0, 0])

In [53]:
zeros_arr = zeros_arr.astype(float)
zeros_arr

array([0., 0., 0., 0., 0.])

In [54]:
arr2d = np.array([[1,2,3],[2,3,4],[2,3,4],[3,4,5]])
arr2d

array([[1, 2, 3],
       [2, 3, 4],
       [2, 3, 4],
       [3, 4, 5]])

In [ ]:
#using shape function
arr2d.shape

(4, 3)

In [ ]:
#shows the dimensions of array
arr2d.ndim

2

In [ ]:
#shows the data type of array
arr.dtype

dtype('int64')

In [58]:
np.swapaxes(arr2d,1,0)

array([[1, 2, 2, 3],
       [2, 3, 3, 4],
       [3, 4, 4, 5]])

In [59]:
arr2d.reshape(3,4)

array([[1, 2, 3, 2],
       [3, 4, 2, 3],
       [4, 3, 4, 5]])

In [60]:
np.linspace(5,15,5, dtype="int")

array([ 5,  7, 10, 12, 15])

In [61]:
arr2d.sort
arr2d

array([[1, 2, 3],
       [2, 3, 4],
       [2, 3, 4],
       [3, 4, 5]])

In [62]:
arr2d.sort(1)
arr2d

array([[1, 2, 3],
       [2, 3, 4],
       [2, 3, 4],
       [3, 4, 5]])

In [63]:
array1=np.array([1.0,2,3,4,5,6])
array1


array([1., 2., 3., 4., 5., 6.])

In [64]:
#shows the dtype of array

array1.dtype

dtype('float64')

In [65]:
#shows the dimensions of array
array1.ndim


1

In [69]:
#shows the dimensions of 2D array
array2=np.array([[1,2,4],[4,6,8]]) #2D dimensional array declare
array2
array2.ndim


2

In [67]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
#print the last element of array
arr[-1]

np.int64(9)

In [72]:
#reshape array into rows and column format
import numpy as np
array3=np.arange(2,11)
b=array3.reshape(3,3)
b

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [ ]:
#print the array and x and y 
#adding the array in 
x=np.array([[1,2,3],[2,3,4]])
y=np.array([[5,6,7],[8,9,10]])
print(x)
print(y)
z=x+y
print(z)



[[1 2 3]
 [2 3 4]]
[[ 5  6  7]
 [ 8  9 10]]
[[ 6  8 10]
 [10 12 14]]


In [ ]:
import numpy as np
array1 = np.array([3, 7, 2, 9, 5])

max_index = array1.argmax()  # index of max value
min_index = array1.argmin()  # index of min value
print("Min value index:", min_index) 
print("Max value index:", max_index) 



Min value index: 2
Max value index: 3
